// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nHkBveSSKzfMQZfdKBOY3NlJzHRk4AU',
    appId: '1:615244517587:web:8cb476ba2d119b4dd38426',
    messagingSenderId: '615244517587',
    projectId: 'chat-app-b1062',
    authDomain: 'chat-app-b1062.firebaseapp.com',
    storageBucket: 'chat-app-b1062.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNmaOkqmG3buVI2nyVFOgNwHvUa90u1U',
    appId: '1:615244517587:android:5874ebe36b10eca5d38426',
    messagingSenderId: '615244517587',
    projectId: 'chat-app-b1062',
    storageBucket: 'chat-app-b1062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLr-bX7ZvFoaVKVbVJ-rMTUh8EnRvZIgc',
    appId: '1:615244517587:ios:ff69ab6ed94abb2bd38426',
    messagingSenderId: '615244517587',
    projectId: 'chat-app-b1062',
    storageBucket: 'chat-app-b1062.appspot.com',
    androidClientId: '615244517587-e37527t35if74un3k3rp6tpijlt6rih6.apps.googleusercontent.com',
    iosClientId: '615244517587-kq989dcighgrrr76fb86ljg5udt4e0kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLr-bX7ZvFoaVKVbVJ-rMTUh8EnRvZIgc',
    appId: '1:615244517587:ios:ff69ab6ed94abb2bd38426',
    messagingSenderId: '615244517587',
    projectId: 'chat-app-b1062',
    storageBucket: 'chat-app-b1062.appspot.com',
    androidClientId: '615244517587-e37527t35if74un3k3rp6tpijlt6rih6.apps.googleusercontent.com',
    iosClientId: '615244517587-kq989dcighgrrr76fb86ljg5udt4e0kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
